---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    name: catalogue
    tier: app
spec:
  containers:
    - name: catalogue
      imagePullPolicy: Always
      image: sivaram1206/catalogue:v1
      resources:
        requests:
          cpu: "150m"
          memory: "125Mi"
        limits:
          cpu: "150m"
          memory: "125Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    name: catalogue
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


