---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
    tier: db
spec:
  containers:
    - name: web
      imagePullPolicy: Always
      image: sivaram1206/mongo:v1
      resources:
        requests:
          cpu: "150m"
          memory: "125Mi"
        limits:
          cpu: "150m"
          memory: "125Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    name: mongo
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017


