---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
    tier: db
spec:
  containers:
    - name: mongo
      imagePullPolicy: Always
      image: sivaram1206/mongo:v1
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    name: mongo
    tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017


